#!/bin/bash
set -e

# ----------------------------- Creating directory ---------------------
mkdir ~/.aws aws aws/cluster aws/ssh cluster && cd cluster

# ----------------------------- Setting AWS credentials ----------------
echo $CONFIG > ~/.aws/config
echo $CREDENTIALS > ~/.aws/credentials
export AWS_ACCESS_KEY_ID=$AC_ID
export AWS_SECRET_ACCESS_KEY=$AC_KEY
export AWS_DEFAULT_REGION=eu-west-2
export AWS_DEFAULT_OUTPUT=json

# ----------------------------- Cloning litmus repository --------------
git clone https://github.com/openebs/litmus.git
#git clone https://github.com/chandankumar4/litmus.git
cd litmus/k8s/aws/k8s-installer

# ------- Creating Pre-requisite for setup AWS cluster -----------------
echo "creating pre-requisite"
ansible-playbook pre-requisite.yml -v

# ----------------------------- Creating AWS Cluster -------------------
echo "creating  AWS cluster"
ansible-playbook create-aws-cluster.yml --extra-vars "k8s_version=1.10.0" -v

# ------------------- Applying rbac.yml of litmus ---------------------
wget https://raw.githubusercontent.com/openebs/litmus/master/hack/rbac.yaml
kubectl apply -f rbac.yaml

# --------------------- Preparing for gitlab artifact ------------------
cat /tmp/aws/cluster_name.csv >/openebs/e2e-aws/aws/cluster/cluster_name.csv
cat /tmp/aws/id.csv > /openebs/e2e-aws/aws/cluster/id.csv
mkdir /openebs/e2e-aws/aws/.kube
cat ~/.kube/config > /openebs/e2e-aws/aws/.kube/admin.conf
cat ~/.kube/config > /openebs/e2e-aws/aws/.kube/config
cp -r ~/.ssh/. /openebs/e2e-aws/aws/ssh

# -------------------------- Applying configmap -------------------------
kubectl create configmap kubeconfig --from-file=/openebs/e2e-aws/aws/.kube/admin.conf -n litmus
