#!/bin/bash
#set -ex

: << EOF
export AWS_ACCESS_KEY_ID=$AC_ID
export AWS_SECRET_ACCESS_KEY=$AC_KEY
export AWS_DEFAULT_REGION=eu-west-2
export AWS_DEFAULT_OUTPUT=json
export ANSIBLE_HOST_KEY_CHECKING=False
mkdir /tmp/aws
mkdir ~/.kube
cp  aws-openebs/config ~/.kube/config
cat aws-openebs/id.csv > /tmp/aws/id.csv
cat aws-openebs/cluster_name.csv >/tmp/aws/cluster_name.csv
cp -r aws-openebs/ssh/. ~/.ssh/


echo "attaching disks"

git clone https://github.com/atulabhi/litmus.git

cd litmus

git checkout v0.7-RC1

cd k8s/aws/ebs-volumes/

cluster=$(cat /tmp/aws/cluster_name.csv | cut -d: -f2)
ansible-playbook create-ebs-volume.yml -vv --extra-vars "cluster_name=nodes.k8s-$cluster.k8s.local"
EOF

echo "Cluster-provision-Stage"
echo "Disks-attached"
