#!/bin/bash
set -e

echo "Deploying statefulapps"

export AWS_ACCESS_KEY_ID=$AC_ID
export AWS_SECRET_ACCESS_KEY=$AC_KEY
export AWS_DEFAULT_REGION=eu-west-2
export AWS_DEFAULT_OUTPUT=json
mkdir /tmp/aws
mkdir ~/.kube
cp  aws-openebs/config ~/.kube/config
cat aws-openebs/id.csv > /tmp/aws/id.csv
cat aws-openebs/cluster_name.csv >/tmp/aws/cluster_name.csv


echo "attaching disks"

git clone https://github.com/atulabhi/litmus.git

cd litmus

git checkout v0.7-RC1

git branch

ls


ls -a


